### ISSUE TITLE
The test docker image seems not exist

### ISSUE THREAD

**Issue by Ddnirvana** [nabla-containers/measurements#5]
Hi guys, 
    I want to try the measurements used in nabla, but I failed when downloading the tested docker image. The runtest.bash will dowload redis/node-express-legacy for example.

I tried the following pull request manually, and found that the image seems not exist.

<pre>
    $ docker pull redis-express-legacy
Using default tag: latest
Error response from daemon: pull access denied for redis-express-legacy, repository does not exist or may require 'docker login'
</pre>

Can you help me about this?
Any advice is welcomed!

**Comment by lumjjb** [comment]
Hi @Ddnirvana! Thanks for trying out the images! 

I believe the commands used were with local images that were built from scratch. For convenience, we have also uploaded the images in the `nablact/` namespace in docker hub (https://hub.docker.com/u/nablact/).

Below is an example of pulling them - let me know if this works for you.
```
lumjjb@lumjjb-ThinkPad-P50:~$ docker pull nablact/node-express-legacy
Using default tag: latest
latest: Pulling from nablact/node-express-legacy
03e1855d4f31: Already exists
a3ed95caeb02: Already exists
9269ba3950bb: Already exists
6ecee6444751: Already exists
7a0c192d4d25: Already exists
9e9f27c61394: Already exists
f20b85b68b8c: Already exists
9d0c229e1027: Pull complete
c2a6215d349f: Pull complete
b8ae13a41089: Pull complete
77f015aef083: Pull complete
Digest: sha256:eeee388180010ef07347e51681eea1ca5e34222e893afbd24776042d04988a68
Status: Downloaded newer image for nablact/node-express-legacy:latest
lumjjb@lumjjb-ThinkPad-P50:~$ docker pull nablact/redis-legacy
Using default tag: latest
Error response from daemon: manifest for nablact/redis-legacy:latest not found
lumjjb@lumjjb-ThinkPad-P50:~$ docker pull nablact/redis-test-legacy
Using default tag: latest
latest: Pulling from nablact/redis-test-legacy
d2ca7eff5948: Pull complete
1d1a2245aaa6: Pull complete
9a483dd2a28b: Pull complete
a393fdb1ed0b: Pull complete
88c7e4d61bf3: Pull complete
73875ef81fb3: Pull complete
a3d856352d57: Pull complete
Digest: sha256:1f52dd536dc9c8ed9c07451d28c9e558e745fa177bb3d75d616490335b1718c4
Status: Downloaded newer image for nablact/redis-test-legacy:latest
```

**Comment by djwillia** [comment]
@Ddnirvana, also, just want to point out that your command `docker pull redis-express-legacy` was using the wrong name; it should be `redis-test-legacy` or `node-express-legacy` as shown in @lumjjb 's example.  Just wanted to make sure that you don't get stuck on a typo! :)

**Comment by Ddnirvana** [comment]
Thanks for you guys's help! 
Now I can run with `sudo ./runtest.bash runc nablact/redis-test results/docker-redis-test`, just like your updated ReadMe:)

However, when using redis-test, it will print some error messages.

<pre>
sudo ./runtest.bash runc nablact/redis-test results/docker-redis-test
make: Nothing to be done for 'all'.
Using default tag: latest
latest: Pulling from nablact/redis-test-legacy
Digest: sha256:1f52dd536dc9c8ed9c07451d28c9e558e745fa177bb3d75d616490335b1718c4
Status: Image is up to date for nablact/redis-test-legacy:latest
Using default tag: latest
latest: Pulling from nablact/redis-test-nabla
Digest: sha256:2af7936896180aed11c84b41cb093758ac65795c82af4cf68a80ce2432238bc0
Status: Image is up to date for nablact/redis-test-nabla:latest
## set up kernel ftrace parameters
37c06510709c809517a6c4589e6a6edde9586204503a635dda575a8a0f9513b2
## running nablact/redis-test on runc
pid 4684's current affinity mask: ff
pid 4684's new affinity mask: 1
pid 4685's current affinity mask: ff
pid 4685's new affinity mask: 1
pid 4686's current affinity mask: ff
pid 4686's new affinity mask: 1
pid 4687's current affinity mask: ff
pid 4687's new affinity mask: 1
pid 4688's current affinity mask: ff
pid 4688's new affinity mask: 1
pid 4689's current affinity mask: ff
pid 4689's new affinity mask: 1
pid 4690's current affinity mask: ff
pid 4690's new affinity mask: 1
pid 4691's current affinity mask: ff
pid 4691's new affinity mask: 1
pid 4692's current affinity mask: ff
pid 4692's new affinity mask: 1
pid 4711's current affinity mask: ff
pid 4711's new affinity mask: 1
pid 4781's current affinity mask: ff
pid 4781's new affinity mask: 1
pid 4782's current affinity mask: ff
pid 4782's new affinity mask: 1
taskset: failed to get pid 4803's affinity: No such process
taskset: failed to get pid 4806's affinity: No such process
taskset: failed to get pid 4809's affinity: No such process
taskset: failed to get pid 4812's affinity: No such process
taskset: failed to get pid 4815's affinity: No such process
taskset: failed to get pid 4818's affinity: No such process
taskset: failed to get pid 4821's affinity: No such process
taskset: failed to get pid 4824's affinity: No such process
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
./runtest.bash: line 116: redis-cli: command not found
## finished offering load
## copied trace to directory
tracetest
## killed container
## processed data
</pre>

It seems I need to download redis-cli tool..

**Comment by lumjjb** [comment]
@Ddnirvana did refreshing the redis-cli tool fix the problem?

**Comment by lumjjb** [comment]
Hi @Ddnirvana, are you still running into the problem?

**Comment by djwillia** [comment]
This seems to be resolved
